name: Generate text config

on:
  push:
    branches:
      - main
    paths:
      - 'art/**'
      - 'shell/catalog_git.py'
      - 'shell/generate_text_config.py'
      - '.github/workflows/generate-article-page.yml'

jobs:
  generate-text-config:
    name: Generate text config
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build text config
        run: |
          python ./shell/generate_text_config.py
          cat static/scripts/text-config.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update text config'
          file_pattern: static/scripts/text-config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
