name: Generate config file

on:
  push:
    branches:
      - main
    paths:
      - 'meme/**'
      - 'shell/computed.sh'
      - 'shell/generate_config.py'
      - 'shell/catalog_git.py'
      - '.github/workflows/generate-config-file.yml'

jobs:
  generate-config-file:
    name: Generate config file
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build config
        run: |
          ./shell/computed.sh
          cat static/scripts/config.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update config file'
          file_pattern: static/scripts/config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
